<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Region;
use App\Models\Province;
use App\Models\SiteTouristique;
use App\Models\Festival;
use App\Models\Galerie;

class RegionSeeder extends Seeder
{
    public function run(): void
    {
        $regions = [
            [
                'slug'             => 'kadiogo',
                'nom'              => 'Kadiogo',
                'ancien_nom'       => 'Centre',
                'chef_lieu'        => 'Ouagadougou',
                'zone'             => 'Centre',
                'slogan'           => 'Cœur battant du Burkina',
                'superficie'       => 2805,
                'population'       => 3032668,
                'densite'          => 1081.0,
                'climat'           => 'Soudano-Sahélien',
                'vegetation'       => 'Savane arborée',
                'description'      => 'Le Kadiogo est la région capitale du Burkina Faso, établie selon la nouvelle charte territoriale. Abritant Ouagadougou, le cœur politique, administratif et économique du pays, c\'est une région hautement urbanisée où se mêlent modernité et traditions ancestrales.',
                'histoire'         => 'La région se confond territorialement avec l\'unique province éponyme de Kadiogo. Le nom Kaadyoogo désignait originellement un cours d\'eau sacré qui s\'écoulait près du palais du Moogho Naaba, centre historique du pouvoir coutumier.',
                'langues'          => json_encode(['Mooré', 'Dioula', 'Fula', 'Français']),
                'peuples'          => json_encode(['Mossi', 'Peulh', 'Gourmantché', 'Bissa']),
                'voisins'          => json_encode(['Oubri', 'Nando', 'Nazinon', 'Nakambé', 'Kuilsé']),
                'image_hero'       => 'assets/images/regions/kadiogo/hero.jpg',
                'image_card'       => 'assets/images/regions/kadiogo/card.jpg',
                'image_mini_carte' => 'assets/images/regions/kadiogo/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Kadiogo', 'chef_lieu' => 'Ouagadougou', 'superficie' => 2805, 'population' => 3032668, 'description' => 'Province capitale unique de la région, centre administratif, culturel et économique du pays.'],
                ],
                'sites' => [
                    ['nom' => 'Place de la Nation', 'description' => 'Monument emblématique et centre névralgique de Ouagadougou', 'importance' => 'national', 'image' => 'assets/images/regions/kadiogo/sites/nation.jpg'],
                    ['nom' => 'Musée National du Burkina Faso', 'description' => 'Riches collections sur l\'histoire, l\'art et l\'anthropologie culturelle des communautés burkinabè', 'importance' => 'national', 'image' => 'assets/images/regions/kadiogo/sites/musee.jpg'],
                    ['nom' => 'Village Artisanal de Ouaga', 'description' => 'Centre d\'excellence d\'artisanat d\'art traditionnel et contemporain', 'importance' => 'regional', 'image' => 'assets/images/regions/kadiogo/sites/artisanal.jpg'],
                    ['nom' => 'Parc Urbain Bangr-Weoogo', 'description' => 'Forêt classée en plein centre-ville, véritable poumon vert et réserve de biodiversité de la capitale', 'importance' => 'regional', 'image' => 'assets/images/regions/kadiogo/sites/bangr.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESPACO', 'periode' => 'Février-Mars (Biennale)', 'description' => 'Festival panafricain du cinéma et de la télévision de Ouagadougou, le plus grand événement cinématographique d\'Afrique', 'type' => 'Cinéma'],
                    ['nom' => 'SIAO', 'periode' => 'Octobre-Novembre (Biennale)', 'description' => 'Salon International de l\'Artisanat de Ouagadougou, vitrine de l\'artisanat africain', 'type' => 'Artisanat'],
                    ['nom' => 'Les Récréâtrales', 'periode' => 'Octobre-Novembre (Biennale)', 'description' => 'Résidences panafricaines d\'écriture, de création et de diffusion théâtrales', 'type' => 'Théâtre'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/kadiogo/galerie/1.jpg', 'alt' => 'Place de la Nation', 'titre' => 'Place de la Nation'],
                    ['src' => 'assets/images/regions/kadiogo/galerie/2.jpg', 'alt' => 'Ouagadougou vue aérienne', 'titre' => 'Vue aérienne de Ouaga'],
                    ['src' => 'assets/images/regions/kadiogo/galerie/3.jpg', 'alt' => 'Artisanat local', 'titre' => 'Artisans bronziers au travail'],
                ],
            ],
            [
                'slug'             => 'nando',
                'nom'              => 'Nando',
                'ancien_nom'       => 'Centre-Ouest',
                'chef_lieu'        => 'Koudougou',
                'zone'             => 'Centre-Ouest',
                'slogan'           => 'Cité du cavalier rouge et des valeurs endogènes',
                'superficie'       => 21752,
                'population'       => 1660135,
                'densite'          => 76.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Savane arborée',
                'description'      => 'Nando est une région historique et stratégique du Burkina Faso, reconnue sous sa nouvelle dénomination endogène. Elle se distingue par sa forte identité culturelle Gurunsi et Mossi, et sa tradition de bravoure guerrière.',
                'histoire'         => 'Le terme \'Nando\' est le toponyme originel en langue Gurunsi désignant la ville de Koudougou. Adopté dans le cadre de la revalorisation des identités locales, il incarne l\'histoire de la résistance et de l\'unité des peuples de la région.',
                'langues'          => json_encode(['Mooré', 'Lyélé', 'Nuni', 'Français']),
                'peuples'          => json_encode(['Gurunsi (Lyélé, Nuni)', 'Mossi', 'Peulh']),
                'voisins'          => json_encode(['Bankui', 'Guiriko', 'Sud-Ouest', 'Nazinon', 'Kadiogo', 'Oubri']),
                'image_hero'       => 'assets/images/regions/nando/hero.jpg',
                'image_card'       => 'assets/images/regions/nando/card.jpg',
                'image_mini_carte' => 'assets/images/regions/nando/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Boulkiemdé', 'chef_lieu' => 'Koudougou', 'superficie' => 4269, 'population' => 768796, 'description' => 'Foyer économique et universitaire, poumon industriel du textile de la région.'],
                    ['nom' => 'Sanguié', 'chef_lieu' => 'Réo', 'superficie' => 5178, 'population' => 391617, 'description' => 'Berceau de la culture et des traditions culinaires Lyélé.'],
                    ['nom' => 'Ziro', 'chef_lieu' => 'Sapouy', 'superficie' => 5139, 'population' => 241731, 'description' => 'Zone forestière majeure, riche en biodiversité et ressources naturelles.'],
                    ['nom' => 'Sissili', 'chef_lieu' => 'Léo', 'superficie' => 7166, 'population' => 337078, 'description' => 'Zone frontalière stratégique avec le Ghana, véritable grenier agricole de Nando.'],
                ],
                'sites' => [
                    ['nom' => 'Mares aux crocodiles sacrés de Sabou', 'description' => 'Site mystique séculaire abritant des crocodiles inoffensifs protégés par la coutume', 'importance' => 'national', 'image' => 'assets/images/regions/nando/sites/sabou.jpg'],
                    ['nom' => 'Théâtre Populaire de Koudougou', 'description' => 'Haut lieu de l\'expression artistique et des grands rassemblements culturels', 'importance' => 'national', 'image' => 'assets/images/regions/nando/sites/theatre.jpg'],
                    ['nom' => 'Forêt classée de Tiogo', 'description' => 'Réserve de faune naturelle et patrimoine écosystémique de la région', 'importance' => 'regional', 'image' => 'assets/images/regions/nando/sites/tiogo.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'Nuits Atypiques de Koudougou (NAK)', 'periode' => 'Novembre-Décembre', 'description' => 'Festival emblématique célébrant la musique, les arts de la scène et le métissage culturel', 'type' => 'Musique et Arts'],
                    ['nom' => 'Festival International de Théâtre de Koudougou (FITKO)', 'periode' => 'Octobre', 'description' => 'Rendez-vous international majeur promouvant le théâtre populaire et engagé', 'type' => 'Théâtre'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/nando/galerie/1.jpg', 'alt' => 'Cavalier rouge', 'titre' => 'Place du Cavalier Rouge à Koudougou'],
                    ['src' => 'assets/images/regions/nando/galerie/2.jpg', 'alt' => 'Crocodiles de Sabou', 'titre' => 'Mares de Sabou'],
                ],
            ],
            [
                'slug'             => 'nazinon',
                'nom'              => 'Nazinon',
                'ancien_nom'       => 'Centre-Sud',
                'chef_lieu'        => 'Manga',
                'zone'             => 'Centre-Sud',
                'slogan'           => 'Cité de l\'épervier et patrie du patrimoine de Tiébélé',
                'superficie'       => 11327,
                'population'       => 788341,
                'densite'          => 70.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Savane arborée et forêt claire',
                'description'      => 'Le Nazinon est une région culturellement riche et agropastorale du Burkina Faso. Frontalière avec le Ghana, elle est mondialement réputée pour l\'architecture en terre peinte de la Cour royale de Tiébélé.',
                'histoire'         => 'La région tire sa dénomination officielle de l\'hydronyme \'Nazinon\', le nom endogène du fleuve anciennement appelé Volta Rouge, qui traverse et irrigue son territoire.',
                'langues'          => json_encode(['Mooré', 'Bissa', 'Nuni', 'Kasséna', 'Français']),
                'peuples'          => json_encode(['Mossi', 'Bissa', 'Gurunsi (Kasséna, Nuni)']),
                'voisins'          => json_encode(['Kadiogo', 'Nando', 'Oubri', 'Nakambé']),
                'image_hero'       => 'assets/images/regions/nazinon/hero.jpg',
                'image_card'       => 'assets/images/regions/nazinon/card.jpg',
                'image_mini_carte' => 'assets/images/regions/nazinon/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Bazèga', 'chef_lieu' => 'Kombissiri', 'superficie' => 3969, 'population' => 260382, 'description' => 'Province réputée pour sa production maraîchère, arboricole (mangues) et le chapeau de Saponé.'],
                    ['nom' => 'Zoundwéogo', 'chef_lieu' => 'Manga', 'superficie' => 3428, 'population' => 271501, 'description' => 'Province abritant le chef-lieu régional, pôle administratif et carrefour routier.'],
                    ['nom' => 'Nahouri', 'chef_lieu' => 'Pô', 'superficie' => 3930, 'population' => 256458, 'description' => 'Province frontalière, haut lieu du tourisme culturel kasséna et pôle écotouristique.'],
                ],
                'sites' => [
                    ['nom' => 'Cour royale de Tiébélé', 'description' => 'Ensemble architectural unique de concessions en terre ornées de fresques géométriques faites par les femmes Kasséna', 'importance' => 'mondial', 'image' => 'assets/images/regions/nazinon/sites/tiebele.jpg'],
                    ['nom' => 'Ranch de gibier de Nazinga', 'description' => 'Une des plus riches réserves fauniques d\'Afrique de l\'Ouest, célèbre pour ses troupeaux d\'éléphants', 'importance' => 'national', 'image' => 'assets/images/regions/nazinon/sites/nazinga.jpg'],
                    ['nom' => 'Pic de Nahouri', 'description' => 'Sommet rocheux culminant offrant une vue panoramique sur toute la savane et la frontière ghanéenne', 'importance' => 'national', 'image' => 'assets/images/regions/nazinon/sites/pic.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTHEC', 'periode' => 'Annuel', 'description' => 'Festival de Théâtre et de Contes de l\'espace Nahouri', 'type' => 'Culturel'],
                    ['nom' => 'Gis-Gis', 'periode' => 'Après les récoltes', 'description' => 'Fête traditionnelle de réjouissance et d\'action de grâce en pays Kasséna', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/nazinon/galerie/1.jpg', 'alt' => 'Cour de Tiébélé', 'titre' => 'Fresques de la Cour Royale de Tiébélé'],
                    ['src' => 'assets/images/regions/nazinon/galerie/2.jpg', 'alt' => 'Éléphants de Nazinga', 'titre' => 'Safari au Ranch de Nazinga'],
                ],
            ],
            [
                'slug'             => 'nakambe',
                'nom'              => 'Nakambé',
                'ancien_nom'       => 'Centre-Est',
                'chef_lieu'        => 'Tenkodogo',
                'zone'             => 'Centre-Est',
                'slogan'           => 'Berceau du royaume Mossi et carrefour de l\'hospitalité Bissa',
                'superficie'       => 14710,
                'population'       => 1578074,
                'densite'          => 107.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Savane arborée et forêt claire',
                'description'      => 'Le Nakambé est une région historique majeure, berceau fondateur du premier royaume Mossi à Tenkodogo et terre d\'expression de la riche culture Bissa. Stratégiquement frontalière avec le Togo et le Ghana, elle accueille le pôle de croissance de Bagré.',
                'histoire'         => 'Le nom Nakambé est un hydronyme traditionnel issu de la langue Mooré (signifiant \'La rivière blanche\') désignant le fleuve Volta Blanche qui irrigue et fertilise intensément la région.',
                'langues'          => json_encode(['Bissa', 'Mooré', 'Français']),
                'peuples'          => json_encode(['Bissa', 'Mossi (Yaana, Zaossé)', 'Peulh']),
                'voisins'          => json_encode(['Nazinon', 'Kadiogo', 'Oubri', 'Sirba', 'Gourma']),
                'image_hero'       => 'assets/images/regions/nakambe/hero.jpg',
                'image_card'       => 'assets/images/regions/nakambe/card.jpg',
                'image_mini_carte' => 'assets/images/regions/nakambe/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Boulgou', 'chef_lieu' => 'Tenkodogo', 'superficie' => 8771, 'population' => 681310, 'description' => 'Province abritant le chef-lieu régional, pôle historique et agro-industriel de Bagré.'],
                    ['nom' => 'Kouritenga', 'chef_lieu' => 'Koupèla', 'superficie' => 1658, 'population' => 435557, 'description' => 'Province carrefour commercial dynamique, célèbre pour la ville marchande de Pouytenga.'],
                    ['nom' => 'Koulpélogo', 'chef_lieu' => 'Ouargaye', 'superficie' => 4281, 'population' => 461207, 'description' => 'Province agro-pastorale partageant des frontières internationales stratégiques.'],
                ],
                'sites' => [
                    ['nom' => 'Palais Royal du Naaba Guiguemdé', 'description' => 'Cour royale de Tenkodogo, cœur historique et spirituel du royaume souverain de Zoungrana', 'importance' => 'national', 'image' => 'assets/images/regions/nakambe/sites/palais-tenko.jpg'],
                    ['nom' => 'Pôle de croissance et Lac de Bagré', 'description' => 'Aménagement hydro-agricole géant, zone écotouristique et plus grand réservoir piscicole de la région', 'importance' => 'national', 'image' => 'assets/images/regions/nakambe/sites/bagre.jpg'],
                    ['nom' => 'Marché international de Bittou', 'description' => 'Grand marché de transit frontalier ultra-dynamique reliant le Burkina Faso au corridor togolais', 'importance' => 'regional', 'image' => 'assets/images/regions/nakambe/sites/bittou.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'Festival Culturel Bissa', 'periode' => 'Annuel', 'description' => 'Grand rassemblement de valorisation du patrimoine matériel, des contes et coutumes des communautés Bissa', 'type' => 'Culturel'],
                    ['nom' => 'Fête coutumière du Basga', 'periode' => 'Décembre', 'description' => 'Cérémonie royale d\'action de grâce et de bénédiction présidée par le Roi de Tenkodogo', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/nakambe/galerie/1.jpg', 'alt' => 'Palais de Tenkodogo', 'titre' => 'Cour Royale du Naaba à Tenkodogo'],
                    ['src' => 'assets/images/regions/nakambe/galerie/2.jpg', 'alt' => 'Barrage de Bagré', 'titre' => 'Rizières et aménagement du pôle de Bagré'],
                ],
            ],
            [
                'slug'             => 'kuilse',
                'nom'              => 'Kuilsé',
                'ancien_nom'       => 'Centre-Nord',
                'chef_lieu'        => 'Kaya',
                'zone'             => 'Centre-Nord',
                'slogan'           => 'Cité du cuir et de la résilience culturelle',
                'superficie'       => 19822,
                'population'       => 1875321,
                'densite'          => 95.0,
                'climat'           => 'Sahélien',
                'vegetation'       => 'Steppe et savane arborée dégradée',
                'description'      => 'Kuilsé est une région historique du Burkina Faso, reconnue sous sa nouvelle dénomination endogène. C\'est un pôle de premier plan pour l\'élevage de rente, l\'artisanat du cuir labellisé et l\'extraction minière artisanale et industrielle.',
                'histoire'         => 'Le nom Kuilsé est un toponyme en langue Mooré faisant référence aux cours d\'eau saisonniers et aux bas-fonds sacrés de la région. Historiquement, le territoire correspond aux anciens royaumes Mossi indépendants de Boussouma et de Boulsa.',
                'langues'          => json_encode(['Mooré', 'Fula', 'Français']),
                'peuples'          => json_encode(['Mossi', 'Peulh', 'Yarsé']),
                'voisins'          => json_encode(['Oubri', 'Yaadga', 'Liptako', 'Sirba', 'Kadiogo']),
                'image_hero'       => 'assets/images/regions/kuilse/hero.jpg',
                'image_card'       => 'assets/images/regions/kuilse/card.jpg',
                'image_mini_carte' => 'assets/images/regions/kuilse/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Sanmatenga', 'chef_lieu' => 'Kaya', 'superficie' => 9281, 'population' => 893617, 'description' => 'Province du chef-lieu régional, pôle majeur de la maroquinerie traditionnelle et du commerce du bétail.'],
                    ['nom' => 'Bam', 'chef_lieu' => 'Kongoussi', 'superficie' => 4017, 'population' => 421035, 'description' => 'Province agricole célèbre pour sa production de haricots verts et le lac de Bam.'],
                    ['nom' => 'Namentenga', 'chef_lieu' => 'Boulsa', 'superficie' => 6524, 'population' => 460669, 'description' => 'Province agro-pastorale à forte identité coutumière liée au royaume de Boulsa.'],
                ],
                'sites' => [
                    ['nom' => 'Lac de Dem', 'description' => 'Vaste plan d\'eau naturel et sanctuaire ornithologique, lieu de culte coutumier et de maraîchage', 'importance' => 'national', 'image' => 'assets/images/regions/kuilse/sites/dem.jpg'],
                    ['nom' => 'Musée des arts et du cuir de Kaya', 'description' => 'Centre de conservation du savoir-faire ancestral des artisans tanneurs de la région', 'importance' => 'regional', 'image' => 'assets/images/regions/kuilse/sites/musee-cuir.jpg'],
                    ['nom' => 'Site de fonderie antique de fer de Tiwêga', 'description' => 'Fourneaux de réduction de fer datant du deuxième millénaire, témoins d\'une métallurgie ancienne', 'importance' => 'national', 'image' => 'assets/images/regions/kuilse/sites/tiwega.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FEMA', 'periode' => 'Biennale', 'description' => 'Festival des Étalons de la Maroquinerie de Kaya, célébration du savoir-faire des artisans tanneurs', 'type' => 'Artisanat'],
                    ['nom' => 'Fêtes coutumières de Boussouma', 'periode' => 'Novembre', 'description' => 'Cérémonies traditionnelles de bénédiction des récoltes présidées par le Dima de Boussouma', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/kuilse/galerie/1.jpg', 'alt' => 'Tanneurs de Kaya', 'titre' => 'Artisans tanneurs travaillant le cuir'],
                    ['src' => 'assets/images/regions/kuilse/galerie/2.jpg', 'alt' => 'Lac de Dem', 'titre' => 'Coucher de soleil sur le Lac de Dem'],
                ],
            ],
            [
                'slug'             => 'yaadga',
                'nom'              => 'Yaadga',
                'ancien_nom'       => 'Nord',
                'chef_lieu'        => 'Ouahigouya',
                'zone'             => 'Nord',
                'slogan'           => 'Cité de Naaba Kango et terre de la transition agro-écologique',
                'superficie'       => 16199,
                'population'       => 1720108,
                'densite'          => 106.0,
                'climat'           => 'Sahélien',
                'vegetation'       => 'Steppe et savane arbustive dégradée',
                'description'      => 'Le Yaadga est une région historique du Burkina Faso, reconnue sous sa nouvelle dénomination endogène. Elle se distingue par le rayonnement culturel de l\'ancien royaume du Yatenga et par le dynamisme de ses techniques de restauration des sols (Zaï).',
                'histoire'         => 'Le nom \'Yaadga\' fait directement référence au prince Yadega, fils de Naaba Nassébiri et petit-fils de Naaba Oubri, qui a fondé le grand royaume souverain du Yatenga au XIVe siècle.',
                'langues'          => json_encode(['Mooré', 'Fula', 'Français']),
                'peuples'          => json_encode(['Mossi (Yadsé)', 'Peulh', 'Silmi-Mossi']),
                'voisins'          => json_encode(['Nando', 'Kuilsé', 'Liptako', 'Sourou', 'Oubri']),
                'image_hero'       => 'assets/images/regions/yaadga/hero.jpg',
                'image_card'       => 'assets/images/regions/yaadga/card.jpg',
                'image_mini_carte' => 'assets/images/regions/yaadga/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Yatenga', 'chef_lieu' => 'Ouahigouya', 'superficie' => 6771, 'population' => 824994, 'description' => 'Province du chef-lieu régional, cœur historique de la dynastie royale de Naaba Yadega.'],
                    ['nom' => 'Passoré', 'chef_lieu' => 'Yako', 'superficie' => 4137, 'population' => 461035, 'description' => 'Province agro-pastorale célèbre pour sa forte tradition culturelle et ses marchés locaux.'],
                    ['nom' => 'Zondoma', 'chef_lieu' => 'Gourcy', 'superficie' => 2671, 'population' => 245109, 'description' => 'Foyer historique originel des premiers souverains du Yatenga avant l\'installation à Ouahigouya.'],
                    ['nom' => 'Loroum', 'chef_lieu' => 'Titao', 'superficie' => 2620, 'population' => 188970, 'description' => 'Province septentrionale à vocation pastorale forte et zone d\'élevage de rente.'],
                ],
                'sites' => [
                    ['nom' => 'Palais Royal du Yatenga', 'description' => 'Résidence officielle du Naaba Koom, Roi du Yatenga, et haut lieu des audiences coutumières du vendredi', 'importance' => 'national', 'image' => 'assets/images/regions/yaadga/sites/palais.jpg'],
                    ['nom' => 'Tombeaux des Rois à Naaba-Kango', 'description' => 'Mausolée sacré abritant les sépultures des grands rois et des figures fondatrices de la dynastie', 'importance' => 'national', 'image' => 'assets/images/regions/yaadga/sites/tombeau.jpg'],
                    ['nom' => 'Champs d\'application du Zaï à Gourcy', 'description' => 'Pôle de démonstration mondiale des techniques endogènes de récupération des sols arides inventées dans la région', 'importance' => 'mondial', 'image' => 'assets/images/regions/yaadga/sites/zai.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FIRA', 'periode' => 'Biennale', 'description' => 'Festival International du Rire de Ouahigouya, grand carrefour de l\'humour en Afrique de l\'Ouest', 'type' => 'Culturel'],
                    ['nom' => 'Le Nabasga de Ouahigouya', 'periode' => 'Mai-Juin', 'description' => 'Grande fête rituelle annuelle de bénédiction et d\'action de grâce célébrée par le roi du Yatenga', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/yaadga/galerie/1.jpg', 'alt' => 'Palais de Ouahigouya', 'titre' => 'Cour du Roi du Yatenga'],
                    ['src' => 'assets/images/regions/yaadga/galerie/2.jpg', 'alt' => 'Technique du Zai', 'titre' => 'Restauration des terres par le Zaï'],
                ],
            ],
            [
                'slug'             => 'liptako',
                'nom'              => 'Liptako',
                'ancien_nom'       => 'Sahel',
                'chef_lieu'        => 'Dori',
                'zone'             => 'Nord-Est',
                'slogan'           => 'Terre du Liptako, des dignitaires et de l\'or blanc',
                'superficie'       => 34599,
                'population'       => 813450,
                'densite'          => 24.0,
                'climat'           => 'Sahélien strict',
                'vegetation'       => 'Steppe arbustive et herbeuse',
                'description'      => 'Le Liptako est une région historique majeure du nord-est du Burkina Faso, restructurée à la suite de la scission de l\'ancien Sahel. C\'est un espace à forte vocation pastorale, berceau des cultures Peulh, Touareg et Bella, et grand pôle d\'échanges transfrontaliers.',
                'histoire'         => 'La région tire son nom de l\'ancien Émirat du Liptako, fondé au début du XIXe siècle par l\'émir Sambo. En langue Fulsé, Liptako dérive de l\'expression \'Liba-ta-ko\' signifiant littéralement \'on ne peut pas le terrasser\', symbole d\'insoumission et de bravoure.',
                'langues'          => json_encode(['Fula (Fulfuldé)', 'Tamasheq', 'Gourmantché', 'Français']),
                'peuples'          => json_encode(['Peulh', 'Touareg', 'Bella', 'Gourmantché']),
                'voisins'          => json_encode(['Yaadga', 'Kuilsé', 'Sirba', 'Soum']),
                'image_hero'       => 'assets/images/regions/liptako/hero.jpg',
                'image_card'       => 'assets/images/regions/liptako/card.jpg',
                'image_mini_carte' => 'assets/images/regions/liptako/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Séno', 'chef_lieu' => 'Dori', 'superficie' => 13391, 'population' => 312450, 'description' => 'Province du chef-lieu régional, cœur historique de l\'Émirat et pôle commercial du bétail.'],
                    ['nom' => 'Oudalan', 'chef_lieu' => 'Gorom-Gorom', 'superficie' => 10040, 'population' => 251200, 'description' => 'Province septentrionale réputée pour ses dunes, ses sites artisanaux et ses richesses minières.'],
                    ['nom' => 'Yagha', 'chef_lieu' => 'Sebba', 'superficie' => 11168, 'population' => 249800, 'description' => 'Province agro-pastorale partageant une importante frontière d\'échanges avec le Niger.'],
                ],
                'sites' => [
                    ['nom' => 'Mare d\'Oursi', 'description' => 'Vaste zone humide protégée (Ramsar), sanctuaire ornithologique mondial au milieu des dunes de sable', 'importance' => 'mondial', 'image' => 'assets/images/regions/liptako/sites/oursi.jpg'],
                    ['nom' => 'Marché sahélien de Gorom-Gorom', 'description' => 'Haut lieu d\'échanges multiculturels hebdomadaires où se côtoient éleveurs, commerçants de sel et artisans', 'importance' => 'national', 'image' => 'assets/images/regions/liptako/sites/gorom.jpg'],
                    ['nom' => 'Dunes de Markoye', 'description' => 'Splendides cordons de dunes de sable fin, cadre privilégié pour les caravanes et le tourisme sahélien', 'importance' => 'national', 'image' => 'assets/images/regions/liptako/sites/dunes.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESPA', 'periode' => 'Annuel', 'description' => 'Festival Pastoral de Dori, grande foire d\'exposition du bétail et de valorisation des produits laitiers', 'type' => 'Économique et Culturel'],
                    ['nom' => 'Festival des arts et cultures du Sahel', 'periode' => 'Décembre', 'description' => 'Rassemblement annuel célébrant la musique nomade, les contes peulhs et les parades de dromadaires', 'type' => 'Culturel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/liptako/galerie/1.jpg', 'alt' => 'Mare d\'Oursi', 'titre' => 'Oiseaux sur la Mare d\'Oursi'],
                    ['src' => 'assets/images/regions/liptako/galerie/2.jpg', 'alt' => 'Mine d\'Essakane', 'titre' => 'Infrastructures de la mine d\'or d\'Essakane'],
                ],
            ],
            [
                'slug'             => 'sirba',
                'nom'              => 'Sirba',
                'ancien_nom'       => 'Est (partie nord)',
                'chef_lieu'        => 'Bogandé',
                'zone'             => 'Est',
                'slogan'           => 'Cité de la Sirba, carrefour de la résilience et des valeurs endogènes',
                'superficie'       => 12582,
                'population'       => 715600,
                'densite'          => 57.0,
                'climat'           => 'Soudano-Sahélien',
                'vegetation'       => 'Savane arbustive et steppes herbeuses',
                'description'      => 'La Sirba est une région nouvellement créée à la suite de la réorganisation administrative du pays. Stratégiquement positionnée, elle est le berceau historique des communautés Gourmantché et Peulh du nord-est, structurée autour d\'un grand réseau hydrographique.',
                'histoire'         => 'La région tire son toponyme officiel de la rivière Sirba, un affluent majeur du fleuve Niger qui prend sa source au Burkina Faso, traverse la région et symbolise l\'union, la fertilité et les anciennes routes commerciales.',
                'langues'          => json_encode(['Gourmantché', 'Fula (Fulfuldé)', 'Français']),
                'peuples'          => json_encode(['Gourmantché', 'Peulh', 'Bella']),
                'voisins'          => json_encode(['Liptako', 'Soum', 'Kuilsé', 'Oubri', 'Gourma', 'Tapoa']),
                'image_hero'       => 'assets/images/regions/sirba/hero.jpg',
                'image_card'       => 'assets/images/regions/sirba/card.jpg',
                'image_mini_carte' => 'assets/images/regions/sirba/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Gnagna', 'chef_lieu' => 'Bogandé', 'superficie' => 8169, 'population' => 512400, 'description' => 'Province du chef-lieu régional, pôle commercial d\'élevage et marché d\'intérêt national.'],
                    ['nom' => 'Komondjari', 'chef_lieu' => 'Gayéri', 'superficie' => 4413, 'population' => 203200, 'description' => 'Province agro-pastorale frontalière, pilier historique de la culture Gourmantché.'],
                ],
                'sites' => [
                    ['nom' => 'Vallée et berges de la Sirba', 'description' => 'Écosystème aquatique et paysages fluviaux verdoyants au milieu des zones arides, lieu de pêche et de cultures de décrue', 'importance' => 'national', 'image' => 'assets/images/regions/sirba/sites/sirba-fleuve.jpg'],
                    ['nom' => 'Marché à bétail de Bogandé', 'description' => 'L\'un des plus grands et dynamiques marchés de bétail du pays, attirant des commerçants transfrontaliers', 'importance' => 'national', 'image' => 'assets/images/regions/sirba/sites/marche-cattle.jpg'],
                    ['nom' => 'Falaises et abris sous roche de Gayéri', 'description' => 'Formations géologiques spectaculaires ayant servi de refuges historiques lors des anciennes migrations', 'importance' => 'regional', 'image' => 'assets/images/regions/sirba/sites/falaises.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'Foir\'Est de la Sirba', 'periode' => 'Annuel', 'description' => 'Foire agro-pastorale et culturelle de Bogandé pour la promotion du bétail et des arts du terroir', 'type' => 'Économique et Culturel'],
                    ['nom' => 'Célébrations coutumières de la chefferie', 'periode' => 'Après les récoltes', 'description' => 'Rites traditionnels d\'action de grâce conduits par les chefs coutumiers Gourmantché de la région', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/sirba/galerie/1.jpg', 'alt' => 'Marché de Bogandé', 'titre' => 'Commerce au marché de Bogandé'],
                    ['src' => 'assets/images/regions/sirba/galerie/2.jpg', 'alt' => 'Rivière Sirba', 'titre' => 'Paysage de la rivière Sirba en saison des pluies'],
                ],
            ],
            [
                'slug'             => 'tapoa',
                'nom'              => 'Tapoa',
                'ancien_nom'       => 'Est (partie sud-est)',
                'chef_lieu'        => 'Diapaga',
                'zone'             => 'Est',
                'slogan'           => 'Cité des éléphants et sanctuaire de la biodiversité',
                'superficie'       => 14572,
                'population'       => 462100,
                'densite'          => 32.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Savane boisée et forêts galeries protégées',
                'description'      => 'La Tapoa est une région nouvellement créée, véritable sanctuaire écologique et environnemental du Burkina Faso. Frontalière avec le Niger et le Bénin, elle abrite une biodiversité faunique exceptionnelle au cœur du complexe W-Arly-Pendjari.',
                'histoire'         => 'La région tire sa dénomination officielle de la Tapoa, un cours d\'eau majeur et affluent du fleuve Niger qui traverse et irrigue son territoire sauvage.',
                'langues'          => json_encode(['Gourmantché', 'Fula (Fulfuldé)', 'Français']),
                'peuples'          => json_encode(['Gourmantché', 'Peulh']),
                'voisins'          => json_encode(['Gourma', 'Sirba']),
                'image_hero'       => 'assets/images/regions/tapoa/hero.jpg',
                'image_card'       => 'assets/images/regions/tapoa/card.jpg',
                'image_mini_carte' => 'assets/images/regions/tapoa/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Gobnangou', 'chef_lieu' => 'Diapaga', 'superficie' => 9292, 'population' => 312500, 'description' => 'Province du chef-lieu régional, abritant la majestueuse falaise du Gobnangou et le cœur historique de la chefferie locale.'],
                    ['nom' => 'Dyamongou', 'chef_lieu' => 'Kantchari', 'superficie' => 5280, 'population' => 149600, 'description' => 'Province frontalière ultra-stratégique, pôle d\'échanges commerciaux intenses avec le Niger.'],
                ],
                'sites' => [
                    ['nom' => 'Parc National d\'Arly et Complexe W', 'description' => 'Sanctuaire faunique d\'importance mondiale classé par l\'UNESCO, abritant des éléphants, des lions, des léopards et des grands herbivores', 'importance' => 'mondial', 'image' => 'assets/images/regions/tapoa/sites/arly.jpg'],
                    ['nom' => 'Falaise du Gobnangou', 'description' => 'Muraille rocheuse naturelle spectaculaire s\'étirant sur des dizaines de kilomètres, chargée d\'histoire et de mystères', 'importance' => 'national', 'image' => 'assets/images/regions/tapoa/sites/gobnangou.jpg'],
                    ['nom' => 'Chutes de la Koudou', 'description' => 'Magnifiques cascades et rapides situés dans une zone de forêt galerie préservée de la Tapoa', 'importance' => 'national', 'image' => 'assets/images/regions/tapoa/sites/koudou.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTAPA', 'periode' => 'Annuel', 'description' => 'Festival des Arts et Traditions Populaires de la Tapoa, grand rendez-vous de valorisation de la culture Gourmantché', 'type' => 'Culturel'],
                    ['nom' => 'Cérémonies du Tingbana', 'periode' => 'Avant l\'hivernage', 'description' => 'Rites agraires et spirituels traditionnels d\'action de grâce dédiés aux divinités de la terre et de la brousse', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/tapoa/galerie/1.jpg', 'alt' => 'Parc d\'Arly', 'titre' => 'Faune sauvage dans le Parc d\'Arly'],
                    ['src' => 'assets/images/regions/tapoa/galerie/2.jpg', 'alt' => 'Falaise du Gobnangou', 'titre' => 'Paysage de la falaise du Gobnangou'],
                ],
            ],
            [
                'slug'             => 'oubri',
                'nom'              => 'Oubri',
                'ancien_nom'       => 'Plateau-Central',
                'chef_lieu'        => 'Ziniaré',
                'zone'             => 'Centre',
                'slogan'           => 'Berceau d\'Oubri et sanctuaire de la sculpture sur granit',
                'superficie'       => 8545,
                'population'       => 965158,
                'densite'          => 113.0,
                'climat'           => 'Soudano-Sahélien',
                'vegetation'       => 'Savane arborée et parcs à karités',
                'description'      => 'Oubri est une région historique et culturelle majeure du Burkina Faso, reconnue sous sa nouvelle dénomination endogène. Ce territoire hautement symbolique abrite le site mondialement connu de Laongo et se distingue par son dynamisme dans l\'artisanat d\'art.',
                'histoire'         => 'La région tire son nom officiel de Naaba Oubri, le roi guerrier légendaire et figure fondatrice du royaume Mossi de Ouagadougou au XVe siècle, dont le domaine s\'étendait sur ces terres.',
                'langues'          => json_encode(['Mooré', 'Français']),
                'peuples'          => json_encode(['Mossi']),
                'voisins'          => json_encode(['Kadiogo', 'Nando', 'Nazinon', 'Nakambé', 'Sirba', 'Kuilsé']),
                'image_hero'       => 'assets/images/regions/oubri/hero.jpg',
                'image_card'       => 'assets/images/regions/oubri/card.jpg',
                'image_mini_carte' => 'assets/images/regions/oubri/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Oubritenga', 'chef_lieu' => 'Ziniaré', 'superficie' => 2778, 'population' => 312500, 'description' => 'Province du chef-lieu régional, pôle historique abritant le site de Laongo.'],
                    ['nom' => 'Ganzourgou', 'chef_lieu' => 'Zorgho', 'superficie' => 4149, 'population' => 435458, 'description' => 'Province agro-pastorale dynamique, carrefour routier majeur vers l\'Est du pays.'],
                    ['nom' => 'Kourwéogo', 'chef_lieu' => 'Boussé', 'superficie' => 1618, 'population' => 217200, 'description' => 'Province rurale réputée pour ses initiatives agro-écologiques et son artisanat utilitaire.'],
                ],
                'sites' => [
                    ['nom' => 'Site de sculptures sur granit de Laongo', 'description' => 'Musée d\'art contemporain à ciel ouvert où des artistes du monde entier sculptent directement les blocs de granit de la brousse', 'importance' => 'mondial', 'image' => 'assets/images/regions/oubri/sites/laongo.jpg'],
                    ['nom' => 'Musée de l\'eau de Loumbila', 'description' => 'Espace pédagogique et culturel unique dédié à la préservation et à la mémoire des ressources en eau', 'importance' => 'national', 'image' => 'assets/images/regions/oubri/sites/musee-eau.jpg'],
                    ['nom' => 'Parc animalier de Ziniaré', 'description' => 'Réserve de faune locale aménagée au cœur du chef-lieu régional', 'importance' => 'regional', 'image' => 'assets/images/regions/oubri/sites/parc-ziniare.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'Symposium International de Sculpture de Laongo', 'periode' => 'Biennale', 'description' => 'Biennale artistique internationale réunissant des sculpteurs de premier plan autour du granit de Laongo', 'type' => 'Artistique'],
                    ['nom' => 'Nabasga de Zorgho', 'periode' => 'Annuel', 'description' => 'Grande fête coutumière annuelle de bénédiction des récoltes présidée par le chef traditionnel de Zorgho', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/oubri/galerie/1.jpg', 'alt' => 'Sculptures de Laongo', 'titre' => 'Œuvres sculptées sur le granit de Laongo'],
                    ['src' => 'assets/images/regions/oubri/galerie/2.jpg', 'alt' => 'Barrage de Loumbila', 'titre' => 'Périmètre maraîcher de Loumbila'],
                ],
            ],
            [
                'slug'             => 'goulmou',
                'nom'              => 'Goulmou',
                'ancien_nom'       => 'Est (partie centrale et sud)',
                'chef_lieu'        => 'Fada N\'Gourma',
                'zone'             => 'Est',
                'slogan'           => 'Cité de Yendabili et berceau du grand Goulmou',
                'superficie'       => 33920,
                'population'       => 580000,
                'densite'          => 17.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Savane boisée et forêts denses protégées',
                'description'      => 'Le Goulmou est le royaume central et historique du peuple Gourmantché au Burkina Faso. Réorganisé autour de son chef-lieu Fada N\'Gourma, c\'est un territoire à forte identité culturelle, doté d\'immenses ressources agro-pastorales et énergétiques.',
                'histoire'         => 'Le toponyme endogène \'Goulmou\' fait directement référence au territoire traditionnel des Gourmantché et à l\'ensemble ethnolinguistique unifié au XVIIIe siècle sous le règne du grand roi et conquérant royal Yendabili.',
                'langues'          => json_encode(['Gourmantché', 'Fula (Fulfuldé)', 'Français']),
                'peuples'          => json_encode(['Gourmantché', 'Peulh']),
                'voisins'          => json_encode(['Sirba', 'Tapoa', 'Nakambé', 'Oubri', 'Nazinon']),
                'image_hero'       => 'assets/images/regions/goulmou/hero.jpg',
                'image_card'       => 'assets/images/regions/goulmou/card.jpg',
                'image_mini_carte' => 'assets/images/regions/goulmou/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Gourma', 'chef_lieu' => 'Fada N\'Gourma', 'superficie' => 26051, 'population' => 480000, 'description' => 'Province principale abritant le chef-lieu régional, cœur historique du pouvoir coutumier et de l\'administration.'],
                    ['nom' => 'Kompienga', 'chef_lieu' => 'Pama', 'superficie' => 7869, 'population' => 100000, 'description' => 'Province agro-pastorale majeure, abritant le grand barrage hydroélectrique national.'],
                ],
                'sites' => [
                    ['nom' => 'Palais Royal du Kupiendéli', 'description' => 'Cour royale de Fada N\'Gourma, siège spirituel suprême et lieu de mémoire de la dynastie Gourmantché', 'importance' => 'national', 'image' => 'assets/images/regions/goulmou/sites/palais-fada.jpg'],
                    ['nom' => 'Barrage hydroélectrique de Kompienga', 'description' => 'Premier grand aménagement hydroélectrique du Burkina Faso, formant un immense lac d\'intérêt piscicole et écotouristique', 'importance' => 'national', 'image' => 'assets/images/regions/goulmou/sites/kompienga.jpg'],
                    ['nom' => 'Falaises sacrées de Fada', 'description' => 'Formations géologiques et escarpements naturels, refuges et sanctuaires historiques de rites protecteurs', 'importance' => 'regional', 'image' => 'assets/images/regions/goulmou/sites/falaises.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTICO', 'periode' => 'Annuel', 'description' => 'Festival des Identités Culturelles de Fada N\'Gourma, célébrant la musique, les contes et les traditions du peuple Gourmantché', 'type' => 'Culturel'],
                    ['nom' => 'Le Dilem', 'periode' => 'Novembre', 'description' => 'Fête coutumière et rituelle agraire d\'action de grâce célébrée par le Roi de Fada après les premières récoltes', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/goulmou/galerie/1.jpg', 'alt' => 'Palais de Fada', 'titre' => 'Cour Royale du Roi du Goulmou'],
                    ['src' => 'assets/images/regions/goulmou/galerie/2.jpg', 'alt' => 'Barrage Kompienga', 'titre' => 'Infrastructures du barrage de Kompienga'],
                ],
            ],
            [
                'slug'             => 'bankui',
                'nom'              => 'Bankui',
                'ancien_nom'       => 'Boucle du Mouhoun (partie sud-ouest)',
                'chef_lieu'        => 'Dédougou',
                'zone'             => 'Ouest',
                'slogan'           => 'Grenier du Burkina et patrie des masques sacrés en feuilles',
                'superficie'       => 19722,
                'population'       => 915400,
                'densite'          => 46.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Forêt claire, savane boisée et plaines alluviales',
                'description'      => 'Bankui est une grande région stratégique du Burkina Faso, restructurée à la suite de la création de la région du Sourou. Traversée par le fleuve Mouhoun qui fertilise ses terres, elle s\'impose comme le principal bassin cotonnier et céréalier du pays, doublée d\'un foyer culturel majeur célèbre pour ses traditions de masques.',
                'histoire'         => 'Le toponyme endogène \'Bankui\' (ou Banikuy) fait référence au nom historique du chef-lieu Dédougou. C\'est un terme composé issu des langues locales où \'Ban\' signifie les forêts et \'Kui\' désigne le village ou la concession, symbolisant une cité bâtie sous la protection de la nature.',
                'langues'          => json_encode(['Bwamu', 'Dafing (Marka)', 'Dioula', 'Français']),
                'peuples'          => json_encode(['Bwaba', 'Marka (Dafing)', 'Peulh']),
                'voisins'          => json_encode(['Sourou', 'Guiriko', 'Nando', 'Yaadga']),
                'image_hero'       => 'assets/images/regions/bankui/hero.jpg',
                'image_card'       => 'assets/images/regions/bankui/card.jpg',
                'image_mini_carte' => 'assets/images/regions/bankui/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Mouhoun', 'chef_lieu' => 'Dédougou', 'superficie' => 10237, 'population' => 412500, 'description' => 'Province du chef-lieu régional, pôle administratif, universitaire et carrefour d\'échanges agricoles.'],
                    ['nom' => 'Banwa', 'chef_lieu' => 'Solenzo', 'superficie' => 6720, 'population' => 311200, 'description' => 'Province agricole d\'une fertilité exceptionnelle, pôle majeur de production de coton et de maïs.'],
                    ['nom' => 'Balé', 'chef_lieu' => 'Boromo', 'superficie' => 4978, 'population' => 261700, 'description' => 'Province écotouristique et minière, traversée par l\'axe routier central Ouaga-Bobo.'],
                ],
                'sites' => [
                    ['nom' => 'Parc National des Deux Balé', 'description' => 'Vaste réserve faunique naturelle protégée à Boromo, abritant d\'importants troupeaux d\'éléphants d\'Afrique et de grands herbivores', 'importance' => 'national', 'image' => 'assets/images/regions/bankui/sites/bale-elephants.jpg'],
                    ['nom' => 'Les falaises et le fleuve Mouhoun à Dédougou', 'description' => 'Paysages fluviaux spectaculaires et berges aménagées sur le fleuve éponyme, propices à la pêche traditionnelle', 'importance' => 'national', 'image' => 'assets/images/regions/bankui/sites/mouhoun.jpg'],
                    ['nom' => 'Mausolée de la bataille de Boni', 'description' => 'Lieu historique de mémoire célébrant la grande résistance anticoloniale de la guerre du Bani-Volta', 'importance' => 'national', 'image' => 'assets/images/regions/bankui/sites/boni-memorial.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTIMA', 'periode' => 'Biennale (Mars)', 'description' => 'Festival International des Masques et des Arts de Dédougou, biennale culturelle d\'envergure mondiale célébrant le culte et les sorties de masques africains', 'type' => 'Culturel'],
                    ['nom' => 'FESTRI', 'periode' => 'Annuel', 'description' => 'Festival des Rythmes et Danses du Mouhoun à Solenzo, mettant en valeur le patrimoine musical local', 'type' => 'Musical'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/bankui/galerie/1.jpg', 'alt' => 'Masques au FESTIMA', 'titre' => 'Prestation de masques traditionnels au FESTIMA'],
                    ['src' => 'assets/images/regions/bankui/galerie/2.jpg', 'alt' => 'Éléphants à Boromo', 'titre' => 'Troupeau d\'éléphants traversant les Deux Balé'],
                ],
            ],
            [
                'slug'             => 'sourou',
                'nom'              => 'Sourou',
                'ancien_nom'       => 'Boucle du Mouhoun (partie nord)',
                'chef_lieu'        => 'Tougan',
                'zone'             => 'Ouest',
                'slogan'           => 'Terre du dolo, du riz et de la parenté à plaisanterie',
                'superficie'       => 20931,
                'population'       => 785420,
                'densite'          => 38.0,
                'climat'           => 'Soudano-Sahélien',
                'vegetation'       => 'Savane arbustive et plaines d\'inondation',
                'description'      => 'Le Sourou est une région stratégique majeure du nord-ouest du Burkina Faso, officialisée par la nouvelle charte territoriale. Articulée autour de sa gigantesque vallée hydro-agricole, elle s\'affirme comme le pôle d\'excellence de la riziculture nationale et le berceau de la riche culture Samo.',
                'histoire'         => 'La région tire son toponyme officiel de la rivière Sourou, un affluent essentiel du fleuve Mouhoun. En langue Samo, l\'expression évoque une eau calme ou un canal de vie, symbolisant la fertilité et les aménagements hydrauliques historiques.',
                'langues'          => json_encode(['Samo', 'Marka (Dafing)', 'Bwamu', 'Français']),
                'peuples'          => json_encode(['Samo', 'Marka (Dafing)', 'Bwaba']),
                'voisins'          => json_encode(['Bankui', 'Yaadga']),
                'image_hero'       => 'assets/images/regions/sourou/hero.jpg',
                'image_card'       => 'assets/images/regions/sourou/card.jpg',
                'image_mini_carte' => 'assets/images/regions/sourou/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Sourou', 'chef_lieu' => 'Tougan', 'superficie' => 6979, 'population' => 261400, 'description' => 'Province du chef-lieu régional, pôle historique de l\'ethnie Samo et zone de production maraîchère.'],
                    ['nom' => 'Nayala', 'chef_lieu' => 'Toma', 'superficie' => 6059, 'population' => 202820, 'description' => 'Province à forte identité culturelle, connue pour ses traditions de lutte traditionnelle.'],
                    ['nom' => 'Kossi', 'chef_lieu' => 'Nouna', 'superficie' => 7893, 'population' => 321200, 'description' => 'Province agro-pastorale vaste, grand bassin de production céréalière et de sésame.'],
                ],
                'sites' => [
                    ['nom' => 'Aménagements et Vallée du Sourou', 'description' => 'Immense plaine hydro-agricole irriguée s\'étendant à perte de vue, véritable mer de rizières vertes en plein Sahel', 'importance' => 'national', 'image' => 'assets/images/regions/sourou/sites/vallee.jpg'],
                    ['nom' => 'Arènes de lutte traditionnelle de Toma', 'description' => 'Haut lieu de compétition et d\'expression du sport ancestral et de la bravoure en pays San', 'importance' => 'national', 'image' => 'assets/images/regions/sourou/sites/lutte-toma.jpg'],
                    ['nom' => 'Le Sourou frontalier à Léry', 'description' => 'Site du grand barrage de régulation et point de confluence écologique majeur de la région', 'importance' => 'regional', 'image' => 'assets/images/regions/sourou/sites/barrage-lery.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTAL', 'periode' => 'Biennale', 'description' => 'Festival de la Lutte Traditionnelle de Toma, grand rassemblement biennal célébrant ce patrimoine sportif et culturel endogène', 'type' => 'Sportif et Culturel'],
                    ['nom' => 'Foire agro-sylvo-pastorale du Sourou', 'periode' => 'Annuel', 'description' => 'Grande vitrine d\'exposition et de commercialisation du riz local et des produits de la vallée', 'type' => 'Économique'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/sourou/galerie/1.jpg', 'alt' => 'Rizières du Sourou', 'titre' => 'Récolte mécanique du riz dans la vallée'],
                    ['src' => 'assets/images/regions/sourou/galerie/2.jpg', 'alt' => 'Lutte à Toma', 'titre' => 'Combat lors du tournoi de lutte de Toma'],
                ],
            ],
            [
                'slug'             => 'guiriko',
                'nom'              => 'Guiriko',
                'ancien_nom'       => 'Hauts-Bassins',
                'chef_lieu'        => 'Bobo-Dioulasso',
                'zone'             => 'Ouest',
                'slogan'           => 'Cité de Sya, carrefour de l\'industrie, de la musique et des cultures',
                'superficie'       => 25479,
                'population'       => 2238375,
                'densite'          => 88.0,
                'climat'           => 'Soudanien',
                'vegetation'       => 'Forêt claire, savane arborée et vergers de manguiers',
                'description'      => 'Guiriko est la deuxième région économique et le véritable poumon industriel, agro-alimentaire et culturel du Burkina Faso. Articulée autour de sa métropole Bobo-Dioulasso, elle brille par son métissage ethnique, sa richesse musicale et ses traditions de masques sacrés.',
                'histoire'         => 'Le nom \'Guiriko\' fait référence au Guiriko (ou Gwiriko), un puissant royaume dyula précolonial fondé au XVIIIe siècle par Famagha Ouattara, frère du roi de l\'Empire de Kong, qui unifia les communautés de la région autour de Sya.',
                'langues'          => json_encode(['Dioula', 'Bobo', 'Bwamu', 'Sénoufo', 'Français']),
                'peuples'          => json_encode(['Bobo', 'Bwaba', 'Sénoufo', 'Dyula', 'Peulh']),
                'voisins'          => json_encode(['Bankui', 'Tannounyan', 'Djôrô', 'Nando']),
                'image_hero'       => 'assets/images/regions/guiriko/hero.jpg',
                'image_card'       => 'assets/images/regions/guiriko/card.jpg',
                'image_mini_carte' => 'assets/images/regions/guiriko/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Houet', 'chef_lieu' => 'Bobo-Dioulasso', 'superficie' => 11760, 'population' => 1312500, 'description' => 'Province du chef-lieu régional, pôle industriel, ferroviaire, commercial et culturel majeur d\'Afrique de l\'Ouest.'],
                    ['nom' => 'Tuy', 'chef_lieu' => 'Houndé', 'superficie' => 5383, 'population' => 510200, 'description' => 'Grand bassin agricole cotonnier et pôle d\'extraction minière industrielle (Or).'],
                    ['nom' => 'Kénédougou', 'chef_lieu' => 'Orodara', 'superficie' => 8336, 'population' => 415675, 'description' => 'Le verger du Burkina, zone d\'excellence pour l\'arboriculture (mangues, agrumes) et la culture Sénoufo.'],
                ],
                'sites' => [
                    ['nom' => 'Grande Mosquée de Dioulassoba', 'description' => 'Chef-d\'œuvre d\'architecture de style soudano-sahélien construit en banco au XIXe siècle, monument emblématique de la ville', 'importance' => 'national', 'image' => 'assets/images/regions/guiriko/sites/mosquee.jpg'],
                    ['nom' => 'Quartiers historiques de Dioulassoba', 'description' => 'Cœur originel de Sya avec ses habitations traditionnelles, ses marigots aux silures sacrés et sa forte empreinte coutumière', 'importance' => 'national', 'image' => 'assets/images/regions/guiriko/sites/vieille-ville.jpg'],
                    ['nom' => 'Mare aux hippopotames de Bala', 'description' => 'Réserve de biosphère classée par l\'UNESCO, abritant des dizaines d\'hippopotames et une biodiversité exceptionnelle', 'importance' => 'mondial', 'image' => 'assets/images/regions/guiriko/sites/bala.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'Semaine Nationale de la Culture (SNC)', 'periode' => 'Biennale (Avril)', 'description' => 'La plus grande manifestation culturelle du pays, biennale officielle célébrant les arts plastiques, la littérature et les arts du spectacle', 'type' => 'National / Panafricain'],
                    ['nom' => 'Festival International du Balafon (FIBO)', 'periode' => 'Biennale', 'description' => 'Rendez-vous culturel majeur à Sikasso-Cira / Bobo mettant en compétition les meilleurs joueurs de balafon de la sous-région', 'type' => 'Musical'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/guiriko/galerie/1.jpg', 'alt' => 'Mosquée de Dioulassoba', 'titre' => 'Grande Mosquée de Bobo-Dioulasso'],
                    ['src' => 'assets/images/regions/guiriko/galerie/2.jpg', 'alt' => 'SNC Bobo', 'titre' => 'Parade d\'ouverture de la Semaine Nationale de la Culture'],
                ],
            ],
            [
                'slug'             => 'tannounyan',
                'nom'              => 'Tannounyan',
                'ancien_nom'       => 'Cascades',
                'chef_lieu'        => 'Banfora',
                'zone'             => 'Ouest',
                'slogan'           => 'Cité du pays de l\'or vert, de la canne à sucre et des merveilles de la nature',
                'superficie'       => 18433,
                'population'       => 865100,
                'densite'          => 47.0,
                'climat'           => 'Soudanien humide',
                'vegetation'       => 'Forêt galerie, savane arborée et denses vergers',
                'description'      => 'Tannounyan est la région la plus arrosée et la plus verdoyante du Burkina Faso, reconnue sous sa dénomination endogène. Elle s\'impose comme le pôle majeur de l\'agro-industrie sucrière (SOSUCO) et constitue le principal sanctuaire écotouristique national grâce à ses formations géologiques uniques.',
                'histoire'         => 'Le nom \'Tannounyan\' est un toponyme endogène fort issu des langues locales de l\'Ouest, adopté pour valoriser l\'identité territoriale. Il désigne historiquement les espaces verdoyants et les plaines fertiles de la Comoé et de la Léraba.',
                'langues'          => json_encode(['Dioula', 'Sénoufo', 'Karaboro', 'Turka', 'Français']),
                'peuples'          => json_encode(['Sénoufo', 'Karaboro', 'Turka', 'Gouin']),
                'voisins'          => json_encode(['Guiriko', 'Djôrô']),
                'image_hero'       => 'assets/images/regions/tannounyan/hero.jpg',
                'image_card'       => 'assets/images/regions/tannounyan/card.jpg',
                'image_mini_carte' => 'assets/images/regions/tannounyan/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Comoé', 'chef_lieu' => 'Banfora', 'superficie' => 15202, 'population' => 681300, 'description' => 'Province du chef-lieu régional, grand pôle industriel sucrier, arboricole et touristique.'],
                    ['nom' => 'Léraba', 'chef_lieu' => 'Sindou', 'superficie' => 3231, 'population' => 183800, 'description' => 'Province frontalière, berceau de la culture Sénoufo et célèbre pour ses aiguilles rocheuses.'],
                ],
                'sites' => [
                    ['nom' => 'Cascades de Karfiguéla', 'description' => 'Magnifiques chutes d\'eau naturelles s\'écoulant sur des falaises de grès, au cœur d\'une forêt galerie luxuriante', 'importance' => 'mondial', 'image' => 'assets/images/regions/tannounyan/sites/karfiguela.jpg'],
                    ['nom' => 'Pics de Sindou', 'description' => 'Chaîne géologique spectaculaire d\'aiguilles de grès sculptées par l\'érosion, lieu sacré de la culture Sénoufo', 'importance' => 'mondial', 'image' => 'assets/images/regions/tannounyan/sites/sindou.jpg'],
                    ['nom' => 'Dômes de Fabedougou', 'description' => 'Formations rocheuses monumentales en forme de dômes ou de ruches géantes façonnées par la nature', 'importance' => 'national', 'image' => 'assets/images/regions/tannounyan/sites/fabedougou.jpg'],
                    ['nom' => 'Lac de Tengrela', 'description' => 'Plan d\'eau naturel et mystique permanent, sanctuaire préservé d\'hippopotames et de nénuphars', 'importance' => 'national', 'image' => 'assets/images/regions/tannounyan/sites/tengrela.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTICO', 'periode' => 'Annuel', 'description' => 'Festival Culturel de la Comoé à Banfora, grand rassemblement de valorisation des arts, des danses et de la musique des terroirs', 'type' => 'Culturel'],
                    ['nom' => 'FIRA', 'periode' => 'Biennale', 'description' => 'Festival International des Masques et des Arts de Sindou (et manifestations rituelles locales Sénoufo)', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/tannounyan/galerie/1.jpg', 'alt' => 'Cascades de Karfiguéla', 'titre' => 'Les chutes d\'eau de Karfiguéla'],
                    ['src' => 'assets/images/regions/tannounyan/galerie/2.jpg', 'alt' => 'Pics de Sindou', 'titre' => 'Aiguilles rocheuses de Sindou'],
                ],
            ],
            [
                'slug'             => 'djoro',
                'nom'              => 'Djôrô',
                'ancien_nom'       => 'Sud-Ouest',
                'chef_lieu'        => 'Gaoua',
                'zone'             => 'Ouest',
                'slogan'           => 'Cité de Bafuji, patrie de la statuaire sacrée et du patrimoine de Loropéni',
                'superficie'       => 16282,
                'population'       => 874030,
                'densite'          => 54.0,
                'climat'           => 'Soudanien humide',
                'vegetation'       => 'Forêt claire, savane boisée et denses parcs à nérés',
                'description'      => 'Le Djôrô est une région culturelle et historique majeure du sud-ouest du Burkina Faso, officialisée sous son appellation endogène. Frontalière avec le Ghana et la Côte d\'Ivoire, elle est internationalement réputée pour ses traditions mémorielles, son architecture défensive et les ruines archéologiques de Loropéni classées par l\'UNESCO.',
                'histoire'         => 'Le toponyme endogène \'Djôrô\' (ou Djoro) fait référence au fleuve spirituel et aux rites initiatiques de purification et d\'attachement aux ancêtres chez les communautés Lobi. La région incarne historiquement une terre de liberté rétive aux dominations extérieures, célèbre pour ses guerriers et ses chasseurs.',
                'langues'          => json_encode(['Lobiri', 'Dagara', 'Birifor', 'Français']),
                'peuples'          => json_encode(['Lobi', 'Dagara', 'Birifor', 'Gan', 'Dian']),
                'voisins'          => json_encode(['Guiriko', 'Tannounyan']),
                'image_hero'       => 'assets/images/regions/djoro/hero.jpg',
                'image_card'       => 'assets/images/regions/djoro/card.jpg',
                'image_mini_carte' => 'assets/images/regions/djoro/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Poni', 'chef_lieu' => 'Gaoua', 'superficie' => 8673, 'population' => 315000, 'description' => 'Province du chef-lieu régional, pôle historique, commercial et artisanal de la culture Lobi.'],
                    ['nom' => 'Ioba', 'chef_lieu' => 'Dano', 'superficie' => 3498, 'population' => 253591, 'description' => 'Province agricole fertile, grand foyer de la communauté Dagara.'],
                    ['nom' => 'Bougouriba', 'chef_lieu' => 'Diébougou', 'superficie' => 3690, 'population' => 174914, 'description' => 'Province carrefour, connue pour ses grottes historiques et sa production de tubercules.'],
                    ['nom' => 'Noumbiel', 'chef_lieu' => 'Batié', 'superficie' => 3160, 'population' => 130525, 'description' => 'Province septentrionale à forte vocation agro-pastorale partageant des frontières stratégiques.'],
                ],
                'sites' => [
                    ['nom' => 'Ruines archéologiques de Loropéni', 'description' => 'Imposants murs de pierre de plus de six mètres de haut datant du XIe siècle, premier site du pays inscrit au patrimoine mondial de l\'UNESCO', 'importance' => 'mondial', 'image' => 'assets/images/regions/djoro/sites/loropeni.jpg'],
                    ['nom' => 'Sanctuaire des Rois Gan à Obiré', 'description' => 'Cœur spirituel de la dynastie royale Gan, abritant les sépultures sacrées et les attributs du pouvoir traditionnel', 'importance' => 'national', 'image' => 'assets/images/regions/djoro/sites/obire.jpg'],
                    ['nom' => 'Musée des civilisations du Sud-Ouest de Gaoua', 'description' => 'Important pôle patrimonial conservant les objets cultuels, les fétiches et l\'histoire des peuples de la région', 'importance' => 'national', 'image' => 'assets/images/regions/djoro/sites/musee-gaoua.jpg'],
                    ['nom' => 'Grottes militaires de Diébougou', 'description' => 'Fortifications et galeries souterraines taillées dans la roche, vestiges de l\'histoire défensive précoloniale et coloniale', 'importance' => 'regional', 'image' => 'assets/images/regions/djoro/sites/grottes.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'FESTILOBI', 'periode' => 'Annuel', 'description' => 'Festival Culturel des Communautés du Sud-Ouest, grand rassemblement itinérant célébrant la musique, l\'art culinaire et la parenté', 'type' => 'Culturel'],
                    ['nom' => 'Célébrations rituelles du Djôrô', 'periode' => 'Cyclique (Tous les 7 ans)', 'description' => 'Grandes initiations sacrées périodiques marquant le passage des jeunes à l\'âge adulte', 'type' => 'Traditionnel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/djoro/galerie/1.jpg', 'alt' => 'Ruines de Loropéni', 'titre' => 'Murailles de pierre de Loropéni'],
                    ['src' => 'assets/images/regions/djoro/galerie/2.jpg', 'alt' => 'Balafon Lobi', 'titre' => 'Musiciens jouant du balafon à Gaoua'],
                ],
            ],
            [
                'slug'             => 'soum',
                'nom'              => 'Soum',
                'ancien_nom'       => 'Sahel (partie ouest)',
                'chef_lieu'        => 'Djibo',
                'zone'             => 'Nord',
                'slogan'           => 'Cité de l\'élevage par excellence et patrie du Djelgodji',
                'superficie'       => 14697,
                'population'       => 423500,
                'densite'          => 29.0,
                'climat'           => 'Sahélien strict',
                'vegetation'       => 'Steppe arbustive et herbeuse',
                'description'      => 'Le Soum est une région historique du nord du Burkina Faso, officiellement érigée en région autonome lors de la scission de l\'ancien Sahel. C\'est le plus grand pôle d\'élevage de rente et de pastoralisme du pays, marqué par l\'héritage culturel et la résilience des communautés Peulhes.',
                'histoire'         => 'La région tire sa dénomination officielle de la province historique du Soum. Son territoire se confond avec l\'ancien Émirat peulh du Djelgodji, fondé au XVIIe siècle par les descendants de l\'ancêtre mythique Nassembé, qui instaurèrent une confédération pastorale hautement organisée.',
                'langues'          => json_encode(['Fula (Fulfuldé)', 'Mooré', 'Français']),
                'peuples'          => json_encode(['Peulh', 'Kouroumba (Fulsé)', 'Bella']),
                'voisins'          => json_encode(['Liptako', 'Kuilsé', 'Yaadga', 'Sourou']),
                'image_hero'       => 'assets/images/regions/soum/hero.jpg',
                'image_card'       => 'assets/images/regions/soum/card.jpg',
                'image_mini_carte' => 'assets/images/regions/soum/mini-carte.jpg',
                'provinces' => [
                    ['nom' => 'Soum', 'chef_lieu' => 'Djibo', 'superficie' => 9768, 'population' => 315400, 'description' => 'Province du chef-lieu régional, cœur de l\'ancien émirat du Djelgodji et pôle névralgique du commerce de bétail.'],
                    ['nom' => 'Karo-Péli', 'chef_lieu' => 'Arbinda', 'superficie' => 4929, 'population' => 108100, 'description' => 'Province à forte identité historique Fulsé, connue pour ses sites archéologiques et ses traditions agraires.'],
                ],
                'sites' => [
                    ['nom' => 'Marché international à bétail de Djibo', 'description' => 'L\'un des plus grands marchés de bétail d\'Afrique de l\'Ouest, véritable carrefour économique sahélien', 'importance' => 'national', 'image' => 'assets/images/regions/soum/sites/marche.jpg'],
                    ['nom' => 'Gravures rupestres et collines d\'Arbinda', 'description' => 'Inscriptions préhistoriques, blocs de pierre gravés et vestiges archéologiques témoins d\'un peuplement très ancien', 'importance' => 'national', 'image' => 'assets/images/regions/soum/sites/arbinda-roches.jpg'],
                    ['nom' => 'Mare de Djibo', 'description' => 'Point d\'eau permanent et stratégique, lieu historique d\'abreuvage des grands troupeaux en transhumance', 'importance' => 'regional', 'image' => 'assets/images/regions/soum/sites/mare-djibo.jpg'],
                ],
                'festivals' => [
                    ['nom' => 'Foire au bétail de Djibo', 'periode' => 'Annuel', 'description' => 'Grande foire annuelle d\'exposition des plus beaux spécimens de reproducteurs et de valorisation du savoir-faire des éleveurs', 'type' => 'Économique'],
                    ['nom' => 'Célébrations de la chefferie du Djelgodji', 'periode' => 'Traditionnel', 'description' => 'Rencontres coutumières et rituels mémoriels sous l\'égide de l\'Émir de Djibo', 'type' => 'Culturel'],
                ],
                'galerie' => [
                    ['src' => 'assets/images/regions/soum/galerie/1.jpg', 'alt' => 'Marché de bétail', 'titre' => 'Négociations au marché de Djibo'],
                    ['src' => 'assets/images/regions/soum/galerie/2.jpg', 'alt' => 'Roches d\'Arbinda', 'titre' => 'Gravures rupestres archéologiques'],
                ],
            ],
        ];

        foreach ($regions as $data) {
            $region = Region::create([
                'slug'             => $data['slug'],
                'nom'              => $data['nom'],
                'ancien_nom'       => $data['ancien_nom'],
                'chef_lieu'        => $data['chef_lieu'],
                'zone'             => $data['zone'],
                'slogan'           => $data['slogan'],
                'superficie'       => $data['superficie'],
                'population'       => $data['population'],
                'densite'          => $data['densite'],
                'climat'           => $data['climat'],
                'vegetation'       => $data['vegetation'],
                'description'      => $data['description'],
                'histoire'         => $data['histoire'],
                'langues'          => $data['langues'],
                'peuples'          => $data['peuples'],
                'voisins'          => $data['voisins'],
                'image_hero'       => $data['image_hero'],
                'image_card'       => $data['image_card'],
                'image_mini_carte' => $data['image_mini_carte'],
            ]);
            foreach ($data['provinces'] as $p) { $region->provinces()->create($p); }
            foreach ($data['sites']    as $s) { $region->sites()->create($s); }
            foreach ($data['festivals'] as $f) { $region->festivals()->create($f); }
            foreach ($data['galerie']  as $g) { $region->galerie()->create($g); }
        }
    }
}